version: '3.8'
services:

  redis:
    image: redis:alpine
    networks: [back-tier]

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ropium
    networks: [back-tier]
    deploy:
      placement:
        constraints: [node.role == manager]

  monolito:
    image: pitielnene/tienda-monolito:latest
    environment:
      - REDIS_HOST=redis
    networks: [back-tier]
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s

  worker:
    image: pitielnene/tienda-monolito:latest
    command: celery -A celery_app worker -l info
    environment:
      - REDIS_HOST=redis
    networks: [back-tier]
    deploy:
      replicas: 5

  ms-pagos:
    image: pitielnene/ms-pagos:latest
    networks: [back-tier]
    deploy:
      replicas: 2

  ms-inventario:
    image: pitielnene/ms-inventario:latest
    networks: [back-tier]
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  gateway:
    image: pitielnene/nginx-gateway:latest
    ports:
      - "80:80"
    networks: [back-tier]
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

networks:
  back-tier:
    driver: overlay

volumes:
  db_data: