services:
  django_web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  flask_order_service:
    build: ./flask_order_service
    container_name: flask_order_service
    ports:
      - "5000:5000"
    volumes:
      - ./flask_order_service:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django_web
      - flask_order_service