services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

  monolito:
    build: .
    container_name: monolito
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - ENV_TYPE=MOCK
      - ALLIED_SERVICE_URL=http://98.95.25.1/api/v2/agenda/therapists/
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - back-tier

  celery_worker:
    build: .
    container_name: celery_worker
    command: sh -c "sleep 5 && celery -A celery_app worker --loglevel=info --concurrency=2"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - .:/app
    depends_on:
      - redis
      - monolito
    networks:
      - back-tier

  ms-pagos:
    build: ./flask_order_service
    container_name: ms-pagos
    networks:
      - back-tier

  ms-inventario:
    build: ./ms_inventario
    container_name: ms-inventario
    networks:
      - back-tier

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - monolito
      - ms-pagos
      - ms-inventario
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
