events {}

http {
    server {
        listen 80;

        location /api/v2/checkout/place-order/ {
            proxy_set_header Host $host;
            proxy_pass http://ms-pagos:5000;
        }

        location / {
            proxy_set_header Host $host;
            proxy_pass http://monolito:8000;
        }
    }
}